"""add user_id to TaskTable

Revision ID: 973c0899a4ea
Revises: 9b4f17d0228a
Create Date: 2026-08-31 16:13:08.467187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '973c0899a4ea'
down_revision: Union[str, Sequence[str], None] = '9b4f17d0228a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
